package com.braisgabin.pokescreenshot.processing;

public class Candy {
  private static String[] CANDY_TYPES = {
      "BULBASAUR",
      "CHARMANDER",
      "SQUIRTLE",
      "CATERPIE",
      "WEEDLE",
      "PIDGEY",
      "RATTATA",
      "SPEAROW",
      "EKANS",
      "PIKACHU",
      "SANDSHREW",
      "NIDORAN♀",
      "NIDORAN♂",
      "CLEFAIRY",
      "VULPIX",
      "JIGGLYPUFF",
      "ZUBAT",
      "ODDISH",
      "PARAS",
      "VENONAT",
      "DIGLETT",
      "MEOWTH",
      "PSYDUCK",
      "MANKEY",
      "GROWLITHE",
      "POLIWAG",
      "ABRA",
      "MACHOP",
      "BELLSPROUT",
      "TENTACOOL",
      "GEODUDE",
      "PONYTA",
      "SLOWPOKE",
      "MAGNEMITE",
      "FARFETCH'D",
      "DODUO",
      "SEEL",
      "GRIMER",
      "SHELLDER",
      "GASTLY",
      "ONIX",
      "DROWZEE",
      "KRABBY",
      "VOLTORB",
      "EXEGGCUTE",
      "CUBONE",
      "HITMONLEE",
      "LICKITUNG",
      "KOFFING",
      "RHYHORN",
      "CHANSEY",
      "TANGELA",
      "KANGASKHAN",
      "HORSEA",
      "GOLDEEN",
      "STARYU",
      "MR. MIME",
      "SCYTHER",
      "JYNX",
      "ELECTABUZZ",
      "MAGMAR",
      "PINSIR",
      "TAUROS",
      "MAGIKARP",
      "LAPRAS",
      "DITTO",
      "EEVEE",
      "PORYGON",
      "OMANYTE",
      "KABUTO",
      "AERODACTYL",
      "SNORLAX",
      "ARTICUNO",
      "ZAPDOS",
      "MOLTRES",
      "DRATINI",
      "MEWTWO",
      "MEW",
  };

  public static String candyType(String text) {
    for (String candy : CANDY_TYPES) {
      if (text.contains(candy.replace(" ", ""))) {
        return candy;
      }
    }
    return null;
  }
}
